# Generated by Django 3.0.4 on 2020-04-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20200410_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='aluno',
            name='CPF',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='bandeira',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='cartao_nome',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='identidade',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='n_cartao',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nascimento',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno'),
        ),
    ]
