# Generated by Django 3.0.4 on 2020-04-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20200410_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno'),
        ),
    ]
