# Generated by Django 3.0.4 on 2020-04-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_auto_20200410_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno'),
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=100)),
                ('aulas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aula')),
            ],
        ),
    ]
