# Generated by Django 3.0.3 on 2020-05-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_auto_20200410_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
    ]
