# Generated by Django 3.0.3 on 2020-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0004_auto_20200514_1955'),
        ('aluno', '0012_auto_20200514_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='planos',
            field=models.ManyToManyField(default=None, to='secretario.Plano'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
    ]
