# Generated by Django 3.0.3 on 2020-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0013_auto_20200514_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
    ]
