# Generated by Django 3.0.3 on 2020-05-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0015_auto_20200518_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_alunos', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aula',
            name='max_alunos',
        ),
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
        migrations.RemoveField(
            model_name='aula',
            name='modalidade',
        ),
        migrations.AddField(
            model_name='aula',
            name='modalidade',
            field=models.ManyToManyField(to='aluno.Modalidade'),
        ),
    ]
