# Generated by Django 3.0.3 on 2020-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0016_auto_20200518_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
    ]
