# Generated by Django 3.0.3 on 2020-05-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
        ('aluno', '0021_auto_20200526_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='exame',
            field=models.ManyToManyField(default=None, to='medico.Exame'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
    ]
