# Generated by Django 3.0.3 on 2020-05-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0033_auto_20200527_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='senha',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
    ]
