# Generated by Django 3.0.3 on 2020-06-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0035_auto_20200603_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno'),
        ),
    ]
