# Generated by Django 3.0.4 on 2020-04-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preço', models.CharField(max_length=100)),
                ('musculação', models.BooleanField(default=False)),
                ('crossfit', models.BooleanField(default=False)),
                ('spinning', models.BooleanField(default=False)),
                ('natação', models.BooleanField(default=False)),
                ('ritmos', models.BooleanField(default=False)),
                ('dividido', models.BooleanField(default=False)),
                ('cancel_enable', models.BooleanField(default=False)),
                ('aval_gratis', models.BooleanField(default=False)),
            ],
        ),
    ]
