# Generated by Django 3.0.4 on 2020-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano_Anual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preço', models.CharField(max_length=100)),
                ('dividido', models.BooleanField(default=True)),
                ('cancel_enable', models.BooleanField(default=True)),
                ('aval_gratis', models.BooleanField(default=True)),
                ('roupa', models.BooleanField(default=False)),
                ('garrafinha', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plano_Mensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preço', models.CharField(max_length=100)),
                ('dividido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plano_Semestral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preço', models.CharField(max_length=100)),
                ('dividido', models.BooleanField(default=True)),
                ('cancel_enable', models.BooleanField(default=False)),
                ('aval_gratis', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
