# Generated by Django 3.0.3 on 2020-05-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('altura', models.CharField(max_length=100)),
                ('pressao', models.CharField(max_length=100)),
                ('pgc', models.CharField(max_length=100)),
                ('pmm', models.CharField(max_length=100)),
                ('IMC', models.CharField(max_length=100)),
                ('habilitado', models.CharField(max_length=4)),
                ('medico', models.ManyToManyField(default=None, to='academia.Academia_Users')),
            ],
        ),
    ]
