# Generated by Django 3.0.3 on 2020-05-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='IMC',
            new_name='imc',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='medico',
        ),
        migrations.AddField(
            model_name='exame',
            name='id_medico',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
