# Generated by Django 3.0.3 on 2020-06-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_auto_20200527_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='id_aluno',
        ),
        migrations.AddField(
            model_name='exame',
            name='cpf_aluno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
