# Generated by Django 3.0.3 on 2020-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_aluno', models.CharField(max_length=100)),
                ('id_do_aluno', models.CharField(max_length=100)),
                ('peito', models.CharField(max_length=100)),
                ('ombro', models.CharField(max_length=100)),
                ('biceps', models.CharField(max_length=100)),
                ('Costas', models.CharField(max_length=100)),
                ('triceps', models.CharField(max_length=100)),
                ('professor', models.ManyToManyField(to='academia.Academia_Users')),
            ],
        ),
    ]
