# Generated by Django 3.0.3 on 2020-05-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='professor',
            field=models.ManyToManyField(default=None, to='academia.Academia_Users'),
        ),
    ]
