# Generated by Django 3.0.3 on 2020-05-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20200525_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='nome_do_aluno',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='id_do_aluno',
        ),
    ]
