# Generated by Django 3.0.3 on 2020-05-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20200525_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='Costas',
            new_name='costas',
        ),
    ]
